### ISSUE TITLE
Keep categories names when updating 

### ISSUE THREAD

**Issue by rebecapastl** [gustante/finans-expense-manager#1]
### Description:

When updating the account information, the fields' titles disappear from the form, what may be a bit confusing to identify which fields need updating.

![Finans 01b](https://user-images.githubusercontent.com/70177784/174484190-30b3de6c-08e3-4f5b-aefc-3c6ff083ff10.png)
![Finans 01a](https://user-images.githubusercontent.com/70177784/174484187-9aa2a1e7-f797-478b-bd30-32dd28db1b73.png)

### Suggested behaviour:
The category names are still visible by the side of each field when the user updates account information

**Comment by gustante** [comment]
Fixed! 
<img width="1429" alt="Screen Shot 2022-06-24 at 6 31 51 PM" src="https://user-images.githubusercontent.com/53026187/175753238-e717a490-3980-4c35-9c4a-7cf1e7731200.png">
