### ISSUE TITLE
Add a button to go back to the current date

### ISSUE THREAD

**Issue by rebecapastl** [gustante/finans-expense-manager#2]
### Descritpion
When adding expanses, some users may have reason to clear all the fields or add a past expanse, changing the date  field...

![Finans 02a](https://user-images.githubusercontent.com/70177784/174484755-045dd516-8bda-4cbd-bc5a-c94cece2702e.png)

... And maybe it would be useful to add a button that would fill back the date with the current date (possibly also fill some other fields like Type with default information).

[Artistic] mock following:

![Finans 02b](https://user-images.githubusercontent.com/70177784/174484961-700f076f-f0ad-47fc-a941-15a1d42b1052.png)

**Comment by gustante** [comment]
Done! Thanks for the suggestion! That's actually really helpful. 

<img width="900" alt="Screen Shot 2022-06-20 at 9 22 24 PM" src="https://user-images.githubusercontent.com/53026187/174715692-e714ccee-c823-4b4a-a5b7-b011bccea1dc.png">
